<?php
$z[0]=Array("global","",12,44);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",107,139);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",229,261);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",328,360);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",430,462);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",535,567);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",646,678);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",976,1002);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",1014,1046);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1093,1119);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("global","",1299,1331);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("channel","\r\n                <li><a href='[field:typeurl/]' title='[field:typename/]' [field:rel/]>[field:typename/]</a></li>\r\n                ",1595,1874);
$z[11][4]['type']="top";
$z[11][4]['row']="8";
$z[11][4]['currentstyle']="<li><a href='~typelink~' class='hover' title='~typename~' ~rel~>~typename~</a></li>";

?>