<?php
$z[0]=Array("global","",620,646);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",690,720);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",757,784);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",790,825);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",995,1027);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1086,1118);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a><span>[field:pubdate function=\"GetDateMK(@me)\"/]</span></li>\r\n          ",2063,2300);
$z[6][4]['row']="5";
$z[6][4]['titlelen']="50";
$z[6][4]['typeid']="2";
$z[7]=Array("global","",2499,2523);
$z[7][4]['name']="dede_left";
$z[8]=Array("arclist","\r\n          <li>\r\n            <div class=\"pic\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" width=\"180\" height=\"166\" /></a></div>\r\n            <div class=\"title\"><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:fulltitle/]\">[field:title/]</a></div>\r\n          </li>\r\n          ",2789,3212);
$z[8][4]['row']="6";
$z[8][4]['typeid']="3";
$z[8][4]['titlelen']="50";
$z[9]=Array("include","",3273,3310);
$z[9][4]['filename']="footer.htm";

?>